name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  ci:
    strategy:
      fail-fast: true

    name: Moon Project
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Foundry 
        uses: foundry-rs/foundry-toolchain@v1

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # The Go version to download (if necessary) and use.

      - name: Setup moon cli
        uses: moonrepo/setup-toolchain@v0

      - name: Run tasks against touched files
        run: moon ci
